DROP PROCEDURE if EXISTS `BHS_DEFAULT_CARRIER_DESTINATION_GetRefSortDestinations` ;
DELIMITER $$
CREATE PROCEDURE  `BHS_DEFAULT_CARRIER_DESTINATION_GetRefSortDestinations` () 
BEGIN 
	SELECT * 
	FROM ref_sort_destinations;
END $$
DELIMITER ;